version: '3.8'
services:
  backend:
    build: .
    container_name: nourane-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nourane
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo:6.0
    container_name: nourane-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: