name: EAS Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - android
        - ios
      profile:
        description: 'Build profile'
        required: true
        default: 'preview'
        type: choice
        options:
        - development
        - preview
        - production
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for EXPO_TOKEN
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
          exit 1
        fi
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test -- --watchAll=false
      
    - name: Build app
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          PLATFORM=${{ github.event.inputs.platform }}
          PROFILE=${{ github.event.inputs.profile }}
        elif [[ "${{ github.ref }}" == "refs/tags/v"* ]]; then
          PLATFORM="all"
          PROFILE="production"
        else
          PLATFORM="all"
          PROFILE="preview"
        fi
        
        if [ "$PLATFORM" == "all" ]; then
          eas build --platform all --profile $PROFILE --non-interactive
        else
          eas build --platform $PLATFORM --profile $PROFILE --non-interactive
        fi