name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release to App Stores
    runs-on: ubuntu-latest
    
    steps:
    # EXPO_TOKEN is required and must be configured in repository secrets
    # This secret should be linked to the project's Expo account
    - name: Check for EXPO_TOKEN
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
          exit 1
        fi
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test -- --watchAll=false
      
    - name: Build production app
      run: eas build --platform all --profile production --non-interactive
      
    - name: Submit to app stores
      run: eas submit --platform all --profile production --non-interactive
      
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Auto-generated release from tag ${{ github.ref }}
        draft: false
        prerelease: false