name: EAS Update

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    
    steps:
    - name: Check for EXPO_TOKEN
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
          exit 1
        fi
        
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test -- --watchAll=false
      
    - name: Publish update
      run: eas update --branch preview --message "Automated update from ${{ github.sha }}"